services:
    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        container_name: project_app
        volumes:
            - ./:/var/www/html
            - ./storage/app/public:/var/www/html/public/storage
        networks:
            - project_network

    nginx:
        build:
            context: .
            dockerfile: _docker/nginx/Dockerfile
        container_name: project_nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www/html
            - ./_docker/nginx/conf.d:/etc/nginx/conf.d
        depends_on:
            - app
            - mysql
            - node
            - laravel-queue
            - laravel-reverb
        networks:
            - project_network

    mysql:
        image: mysql:8.0
        container_name: project_mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        ports:
            - 8123:3306
        volumes:
            - ./_docker/mysql:/var/lib/mysql
        networks:
            - project_network

    laravel-queue:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        container_name: laravel-queue
        restart: on-failure
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        entrypoint: [ 'php', 'artisan', 'queue:work' ]
        depends_on:
            - mysql
        networks:
            - project_network

    laravel-reverb:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        container_name: laravel-reverb
        restart: on-failure
        ports:
            - ${REVERB_PORT}:${REVERB_SERVER_PORT}
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        entrypoint: [ 'php', 'artisan', 'reverb:start', '--debug' ]
        depends_on:
            - mysql
        networks:
            - project_network

    node:
        build:
            context: .
            dockerfile: _docker/node/Dockerfile
        container_name: project_node
        ports:
            - 5173:5173
        restart: on-failure
        volumes:
            - ./:/var/www/html
        depends_on:
            - app
        networks:
            - project_network

networks:
    project_network:
        driver: bridge
